# Generated by Django 4.2.5 on 2023-09-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shipping_address',
            old_name='Product',
            new_name='product',
        ),
    ]
