# Generated by Django 4.2.5 on 2023-09-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_orderd',
        ),
    ]
