# Generated by Django 4.2.5 on 2023-09-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_date_ordered_order_date_orderd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_address',
            name='product',
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
